Join table for visits (PR)
teke85/Vet-clinic-database pull request #4
Opened 2023-03-03 14:51 UTC by teke85

**Learning Objectives:**
- Understand the different types of relationships between tables.
- Prepare complex queries that answer analytical questions.
- Use primary key & foreign key mechanism for joining tables.

**Project requirements:**
- Create a table named vets with the following columns:
id: integer (set it as autoincremented PRIMARY KEY)
name: string
age: integer
date_of_graduation: date
There is a many-to-many relationship between the tables species and vets: a vet can specialize in multiple species, and a species can have multiple vets specialized in it. Create a "join table" called specializations to handle this relationship.
There is a many-to-many relationship between the tables animals and vets: an animal can visit multiple vets and one vet can be visited by multiple animals. Create a "join table" called visits to handle this relationship, it should also keep track of the date of the visit.
- Insert the following data for vets:
Vet William Tatcher is 45 years old and graduated Apr 23rd, 2000.
Vet Maisy Smith is 26 years old and graduated Jan 17th, 2019.
Vet Stephanie Mendez is 64 years old and graduated May 4th, 1981.
Vet Jack Harkness is 38 years old and graduated Jun 8th, 2008.
- Insert the following data for specialties:
Vet William Tatcher is specialized in Pokemon.
Vet Stephanie Mendez is specialized in Digimon and Pokemon.
Vet Jack Harkness is specialized in Digimon.
- Insert the following data for visits:
Agumon visited William Tatcher on May 24th, 2020.
Agumon visited Stephanie Mendez on Jul 22th, 2020.
Gabumon visited Jack Harkness on Feb 2nd, 2021.
Pikachu visited Maisy Smith on Jan 5th, 2020.
Pikachu visited Maisy Smith on Mar 8th, 2020.
Pikachu visited Maisy Smith on May 14th, 2020.
Devimon visited Stephanie Mendez on May 4th, 2021.
Charmander visited Jack Harkness on Feb 24th, 2021.
Plantmon visited Maisy Smith on Dec 21st, 2019.
Plantmon visited William Tatcher on Aug 10th, 2020.
Plantmon visited Maisy Smith on Apr 7th, 2021.
Squirtle visited Stephanie Mendez on Sep 29th, 2019.
Angemon visited Jack Harkness on Oct 3rd, 2020.
Angemon visited Jack Harkness on Nov 4th, 2020.
Boarmon visited Maisy Smith on Jan 24th, 2019.
Boarmon visited Maisy Smith on May 15th, 2019.
Boarmon visited Maisy Smith on Feb 27th, 2020.
Boarmon visited Maisy Smith on Aug 3rd, 2020.
Blossom visited Stephanie Mendez on May 24th, 2020.
Blossom visited William Tatcher on Jan 11th, 2021.
- Write queries to answer the following:
Who was the last animal seen by William Tatcher?
How many different animals did Stephanie Mendez see?
List all vets and their specialties, including vets with no specialties.
List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
What animal has the most visits to vets?
Who was Maisy Smith's first visit?
Details for most recent visit: animal information, vet information, and date of visit.
How many visits were with a vet that did not specialize in that animal's species?
What specialty should Maisy Smith consider getting? Look for the species she gets the most.
- Take a screenshot of the results of your queries.
- Remember to add the screenshot with the results of your queries to your Pull Request description.

## Screenshots
![Desktop screenshot](https://user-images.githubusercontent.com/29442846/222750625-b224ca96-07cf-49fc-b20f-a25d24d52fe2.jpg)
![Desktop screenshot (1)](https://user-images.githubusercontent.com/29442846/222750876-5d115384-08b6-4554-b673-1c95983d5bc5.jpg)
![Desktop screenshot (2)](https://user-images.githubusercontent.com/29442846/222750695-840c93b3-c9fe-43a6-b8ff-772ab7841b07.jpg)
![Desktop screenshot (3)](https://user-images.githubusercontent.com/29442846/222750674-4091e252-c3bb-4505-8c0f-df0d9b79cd57.jpg)

2023-03-03 17:02 UTC, Gambit142 requested changes
Hi @teke85 👋, 

Good job so far!

## Highlights
- Everything that creates or changes the structure of the tables is in the _**schema.sql**_ file
- Everything that populates tables with data is in the _**data.sql**_ file
- Everything that is a query that helps to analyze data is in the _**queries.sql**_ file

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-03 17:02 UTC, Gambit142 commented on queries.sql
> +LIMIT 1;
- [ ] This query asks who was Maisy Smith's first visit. Currently, you are showing us the date of Maisy Smith's first visit but not the name of the animal that visited. It would be nice to include the name of the animal. Kindly update your screenshot after making the change. 👍

2023-03-03 17:02 UTC, Gambit142 commented on queries.sql
> +
- [ ] This query returns the wrong result. The query should return the total number of visits by animals to vets who were not specialized in the animal's species. For this, the result should be 12. This is the breakdown:

- William Thatcher who specializes in Pokemon had 2 visits by Digimon
- Jack Harkness who specializes in Digimon had 1 visit by a Pokemon
- Maisy Smith doesn't specialize in any species but had 9 visits. 

This makes a total of 12 visits. 


#### Hint: You don't have foreign keys for species_id in `animals` table that references species(id). I would advise you set up one in your schema.sql file. Please, don't forget to update your screenshot 👍 😎

2023-03-03 17:02 UTC, Gambit142 commented on queries.sql
> +
- [ ] Maisy Smith had 9 visits from animals. The analysis of the visits is thus:

- Digimon - 6
- Pokemon - 3

Considering the above, it is normal to assume that Maisy Smith should consider being a vet for Digimon species. Your current query returns 0. I would advise you to write a query that reflects this analysis by returning the highest number of animal species that visited Maisy Smith. 👍 😎 

#### Hint: You don't have foreign keys for species_id in `animals` table that references species(id). I would advise you set up one in your schema.sql file. Please, don't forget to update your screenshot 👍 😎

2023-03-03 17:28 UTC, teke85 commented on queries.sql
> +LIMIT 1;
Hi @Gambit142 Thank you very much for the observation. I have created another query which includes the name of the animal, the vet and the date. I have uploaded an updated screenshot in the PR comment section.

2023-03-03 17:38 UTC, teke85 commented on queries.sql
> +
Hi @Gambit142 Thank you so much for the hint bro you have made my work easier lol 👍🏽 😄 I have updated the screenshot and included it in the PR comment section at the top.

2023-03-04 06:31 UTC, teke85 commented on queries.sql
> +
Hi @Gambit142 once again I am grateful for the hint. I have uploaded the updated screenshot at the top of the PR comment section. 🙏🏽

2023-03-04 06:38 UTC, MahmoudBakr23 approved these changes
Hi @teke85 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done on making the requested changes from the previous reviewer
- Excellent communication with the reviewer

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 06:43 UTC, merged